---
- name: Установка Docker и запуск контейнера
  hosts: srv-mink
  become: yes

  tasks:
    - name: Установка зависимостей Docker
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Добавление Docker GPG ключа
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление Docker репозитория
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка Docker
      apt:
        name: docker-ce
        state: present

    - name: Запуск Docker сервиса
      service:
        name: docker
        state: started
        enabled: yes

